# Render.yaml configuration for Airtasker Bot Manager
# Updated configuration to use Docker for system dependencies

services:
  - type: web
    name: airtasker-bot-manager-v2
    runtime: docker
    plan: standard # You can change to starter for a lower-tier plan
    repo: https://github.com/Jogenius22/AutomationFlask.git
    branch: main
    # No build command needed for Docker
    # Docker will use the Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true # Generates a secure random value
      - key: CAPSOLVER_API_KEY
        sync: false # Prompt for this value in the Render Dashboard
    disk:
      name: airtasker_data_v2
      mountPath: /app/data
      sizeGB: 2 # Adjust based on your needs
    healthCheckPath: /
